In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [6]:
baseballDt=pd.DataFrame.from_csv("D:\python_codes\datasets\\baseball\\baseball.csv")

In [11]:
print "the shape of the Dataset is " + str(baseballDt.shape)
print baseballDt.dtypes

the shape of the Dataset is (21699, 21)
year       int64
stint      int64
team      object
lg        object
g          int64
ab         int64
r          int64
h          int64
X2b        int64
X3b        int64
hr         int64
rbi      float64
sb       float64
cs       float64
bb         int64
so       float64
ibb      float64
hbp      float64
sh       float64
sf       float64
gidp     float64
dtype: object

In [47]:
names=baseballDt.columns.tolist()
baseballDt[names].isnull().apply(np.sum)

year        0
stint       0
team        0
lg         65
g           0
ab          0
r           0
h           0
X2b         0
X3b         0
hr          0
rbi        12
sb        250
cs       4525
bb          0
so       1305
ibb      7528
hbp       377
sh        960
sf       7390
gidp     5272
dtype: int64

In [28]:
baseballDt.describe().drop('count')

,year,stint,g,ab,r,h,X2b,X3b,hr,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,gidp
mean,1961.067791,1.092723,72.817641,225.404903,31.780497,61.756901,10.452417,2.194064,5.234204,29.586573,5.168353,2.099744,22.494723,29.262234,2.291793,1.543195,3.388013,1.842477,4.773726
std,33.081972,0.309424,51.645925,215.895195,35.518542,64.065232,11.756606,3.469365,8.783342,33.835287,10.487860,3.645585,26.846263,31.147479,4.217385,2.678309,5.138119,2.561311,5.727964
min,1871.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1937.000000,1.000000,29.000000,25.000000,2.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1970.000000,1.000000,59.000000,131.000000,15.000000,32.000000,5.000000,1.000000,1.000000,14.000000,1.000000,0.000000,11.000000,19.000000,0.000000,0.000000,1.000000,1.000000,2.000000
75%,1988.000000,1.000000,125.000000,435.000000,58.000000,119.000000,19.000000,3.000000,7.000000,51.000000,5.000000,3.000000,38.000000,45.000000,3.000000,2.000000,5.000000,3.000000,8.000000
max,2007.000000,4.000000,165.000000,705.000000,177.000000,257.000000,64.000000,28.000000,73.000000,184.000000,130.000000,42.000000,232.000000,189.000000,120.000000,51.000000,52.000000,19.000000,36.000000

In [62]:

dir(pd.core.groupby.DataFrameGroupBy)

['__bytes__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__iter__',
 '__len__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_aggregate_generic',
 '_aggregate_item_by_item',
 '_aggregate_multiple_funcs',
 '_apply_filter',
 '_apply_to_column_groupbys',
 '_apply_whitelist',
 '_block_agg_axis',
 '_choose_path',
 '_concat_objects',
 '_constructor',
 '_cumcount_array',
 '_cython_agg_blocks',
 '_cython_agg_general',
 '_cython_transform',
 '_decide_output_index',
 '_def_str',
 '_define_paths',
 '_dir_additions',
 '_dir_deletions',
 '_get_data_to_aggregate',
 '_get_index',
 '_get_indices',
 '_group_selection',
 '_index_with_as_index',
 '_insert_inaxis_grouper_inplace',
 '_internal_names',
 '_internal_names_set',
 '_iterate_column_groupbys',
 '_iterate_slices',
 '_make_wrapper',
 '_obj_with_exclusions',
 '_post_process_cython_aggregate',
 '_python_agg_general',
 '_python_apply_general',
 '_reindex_output',
 '_reset_cache',
 '_selected_obj',
 '_selection_list',
 '_set_result_index_ordered',
 '_set_selection_from_grouper',
 '_transform_general',
 '_transform_item_by_item',
 '_try_cast',
 '_wrap_agged_blocks',
 '_wrap_aggregated_output',
 '_wrap_applied_output',
 '_wrap_generic_output',
 '_wrap_transformed_output',
 'agg',
 'aggregate',
 'all',
 'any',
 'apply',
 'bfill',
 'boxplot',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cumcount',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'dtypes',
 'ffill',
 'fillna',
 'filter',
 'first',
 'get_group',
 'groups',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'indices',
 'irow',
 'last',
 'mad',
 'max',
 'mean',
 'median',
 'min',
 'name',
 'ngroups',
 'nth',
 'ohlc',
 'pct_change',
 'plot',
 'prod',
 'quantile',
 'rank',
 'resample',
 'sem',
 'shift',
 'size',
 'skew',
 'std',
 'sum',
 'tail',
 'take',
 'transform',
 'tshift',
 'var']

In [66]:
baseballDt.head()
baseballDt.groupby('lg').size()

lg
AA      171
AL    10007
FL       37
NL    11378
PL       32
UA        9
dtype: int64

In [ ]:
    print baseballDt[col].value_counts